spring:
    datasource:
      url: jdbc:mysql://39.106.71.98:3306/shrio?useUnicode=true&characterEncoding=UTF-8
      username: hxf
      password: hxf
      #schema: database/import.sql
      sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5